# Base skill thresholds
skill_thresholds_young = {"Motor Skills": {# Newborn
                                          20: "Grasping fingers", 
                                          50: "Lifting head while on tummy",
                                          120: "Moving arms and legs",
                                          200: "Bringing hands to mouth",
                                          # Infant
                                          300: "Reaching and Grasping: Learning to reach for and grasp objects.",
                                          400: "Rolling Over: Rolling over from front to back and back to front.", 
                                          500: "Sitting Up: Sitting up without support.", 
                                          600: "Crawling: Moving on hands and knees.",
                                          700: "Standing: Standing with support.",
                                          800: "Cruising: Walking while holding onto furniture.", 
                                          900: "Pulling Up: Pulling up from sitting to standing position.",
                                          # Toddler
                                          1000: "Walking independently: Moving around without support.",
                                          1100: "Running: Beginning to run with coordination.",
                                          1200: "Jumping: Being able to jump with both feet off the ground.",
                                          1300: "Climbing: Climbing onto furniture or playground equipment.",
                                          1400: "Building: Stacking blocks to make a tower.",
                                          1500: "Drawing: Scribbling with crayons or markers.",
                                          1600: "Throwing: Throwing a ball with some accuracy."
                                          },
                        "Social Skills": {# Newborn
                                          20: "Smiling at faces", 
                                          80: "Making eye contact",
                                          110: "Reacting to familiar voices",
                                          110: "Mimicking simple facial expressions (sticking out tongue)",
                                          200: "Cooing and babbling",
                                          # Infant
                                          300: "Social Smiling: Smiling in response to others.",
                                          400: "Recognizing Familiar Faces: Showing preference for familiar people.",
                                          500: "Imitating Movements: Copying simple actions of caregivers.", 
                                          600: "Interactive Play: Engaging in simple games like peek-a-boo.",
                                          700: "Separation Anxiety: Showing distress when separated from parents.",
                                          800: "Showing interest in other children",
                                          # Toddler
                                          1000: "Parallel Play: Playing alongside other children but not directly with them.",
                                          1100: "Sharing: Beginning to share toys and take turns.",
                                          1200: "Showing Empathy: Comforting others when they are upset.",
                                          1300: "Pretend Play: Engaging in simple make-believe games.",
                                          1400: "Following Simple Rules: Understanding and following basic game rules.",
                                          1500: "Playing with Others: Enjoying playing interactive games with other children.",
                                          1600: "Expressing preferences and dislikes clearly"
                                          
                                          },
                        "Emotional Skills": {# Newborn
                                          10: "Showing distress (crying)", 
                                          70: "Self-soothing (sucking thumb)",
                                          150: "Reacting to comfort (calming down when held)",
                                          200: "Expressing joy (smiling)",
                                          250: "Reacting to changes in environment with distress or curiosity",
                                          # Infant
                                          300: "Expressing Emotions: Displaying a range of emotions like joy, anger, and fear.",
                                          400: "Attachment Formation: Developing strong emotional bonds with caregivers.",
                                          500: "Self-Soothing: Seeking comfort from caregivers when upset.",
                                          600: "Identifying strangers with anxiety and fear of unfamiliar faces",
                                          700: "Self-Soothing: Starting to calm themselves when upset.",
                                          # Toddler
                                          1000: "Expressing Frustration: Showing and managing feelings of frustration.",
                                          1100: "Calming Down: Learning to calm down with less help from adults.",
                                          1200: "Showing Affection: Giving hugs, kisses, or showing affection.",
                                          1300: "Recognizing Emotions: Identifying basic emotions in themselves and others.",
                                          1400: "Coping with Transitions: Handling changes in routine with less difficulty.",
                                          1500: "Increasing Independence: Doing small tasks independently, like dressing.",
                                          1600: "Accepting minor disappointments (e.g., waiting for a turn)"
                                                },
                        "Communication Skills": { # Newborn
                                          20: "Cooing to communicate", 
                                          40: "Crying differently for different needs",
                                          160: "Responding to sounds",
                                          200: "Mimicking sounds",
                                          240: "Turning head towards familiar voices",
                                          280: "Recognizing and reacting to changes in tone of voice",
                                          # Infant
                                          300: "Babbling: Experimenting with syllables and sounds.", 
                                          400: "Responding to Name: Turning head towards sounds.",
                                          500: "Gesturing: Using hands to communicate, such as waving or pointing.", 
                                          600: "First Words: Saying simple words like 'mama' or 'dada'.",
                                          800: "Following simple instructions (e.g., 'come here')",
                                          # Toddler
                                          1000: "Speaking in Sentences: Forming simple sentences.",
                                          1100: "Asking Questions: Asking simple questions like 'What’s that?' or 'Why?'",
                                          1200: "Following Directions: Understanding and following two-step directions.",
                                          1300: "Naming Objects: Naming familiar objects, animals, and people.",
                                          1400: "Using Pronouns: Correctly using words like 'I,' 'me,' 'you,' etc.",
                                          1500: "Engaging in Conversations: Starting and maintaining simple conversations."
                                          }, 
                        "Cognitive Skills": {# Newborn
                                          30: "Tracking objects with eyes", 
                                          70: "Recognizing familiar faces",
                                          130: "Showing curiosity (staring at new objects)",
                                          200: "Reacting to changes in environment (startling)",
                                          # Infant
                                          300: "Exploring objects and toys with hands and mouth",
                                          400: "Object Permanence: Understanding that objects continue to exist even when out of sight.",
                                          500: "Cause and Effect: Realizing that actions can cause reactions, like shaking a rattle to make noise.",
                                          600: "Exploring with Senses: Using sight, touch, taste, smell, and hearing to learn about the world.",
                                          700: "Problem Solving: Simple problem-solving like finding hidden objects.",
                                          800: "Imitating actions and sounds",
                                          # Toddler
                                          1000: "Sorting Shapes and Colors: Sorting objects by shape and color.",
                                          1100: "Puzzles: Solving simple puzzles.",
                                          1200: "Counting: Counting objects up to ten.",
                                          1300: "Understanding Time: Grasping basic concepts of time, like morning or night.",
                                          1400: "Matching: Matching pictures to real objects.",
                                          1500: "Pretend Play: Using imagination to play."
                                          }, 
                        "Physical Development": {# Newborn
                                                40: "Displaying strengthened neck muscles", 
                                                80: "Beginning to move arms and legs", 
                                                120: "Coordinating sucking, swallowing, and breathing",
                                                180: "Showing improved coordination of limbs",
                                                # Infant
                                                300: "Teething: Beginning to get their first teeth.",
                                                400: "Eating Solid Foods: Starting to eat baby-friendly solid foods.",
                                                500: "Improved Hand-Eye Coordination: Better control over movements to interact with objects.",
                                                600: "Gaining control over head and neck",
                                                 # Toddler
                                                1000: "Improved Balance: Maintaining balance while walking or running.",
                                                1100: "Fine Motor Skills: Using fingers for tasks like turning pages or stringing beads.",
                                                1200: "Coordination: Coordinating movements like catching a ball.",
                                                1300: "Toilet Training: Learning to use the potty.",
                                                1400: "Feeding Themselves: Using utensils to eat with less mess.",
                                                1500: "Dressing Themselves: Putting on and taking off simple clothing."
                                          } }  


# Change the types of skills

# Academic Skills: Reading, writing, mathematics, and problem-solving abilities.
# Social Skills: Making friends, teamwork, empathy, and conflict resolution.
# Emotional Skills: Recognizing and managing emotions, developing self-esteem, and coping with stress.
# Physical Development: Fine and gross motor skills, coordination, and overall physical fitness.
# Cognitive Skills: Critical thinking, decision-making, and creativity.
# Communication Skills: Verbal and non-verbal communication, listening skills, and public speaking
# Life Skills: Responsibility, time management, organization, and independence.

skill_thresholds_school = {
                              "Academic Skills": {
                                  100: "Identifying shapes and colors",
                                  200: "Recognizing letters and numbers",
                                  300: "Reading simple sentences and basic addition",
                                  400: "Writing simple sentences and solving basic math problems",
                                  500: "Reading comprehension and basic multiplication",
                                  600: "Writing paragraphs and solving word problems",
                                  700: "Reading chapter books and understanding fractions",
                                  800: "Writing essays and solving algebraic equations",
                                  900: "Analyzing literature and understanding geometry",
                                  1000: "Advanced problem-solving and critical thinking",
                              },
                              "Social Skills": {
                                  100: "Playing alongside other children",
                                  200: "Sharing toys and taking turns",
                                  300: "Following simple group rules",
                                  400: "Playing cooperatively and making friends",
                                  500: "Expressing feelings appropriately",
                                  600: "Working in small groups",
                                  700: "Building friendships and handling conflicts",
                                  800: "Showing empathy and understanding others' perspectives",
                                  900: "Collaborating on projects",
                                  1000: "Resolving conflicts and developing leadership skills",
                              },
                              "Emotional Skills": {
                                  100: "Recognizing basic emotions (happy, sad, angry)",
                                  200: "Expressing needs and wants verbally",
                                  300: "Coping with minor frustrations",
                                  400: "Managing separation anxiety",
                                  500: "Developing self-esteem",
                                  600: "Identifying personal strengths",
                                  700: "Handling peer pressure",
                                  800: "Dealing with stress",
                                  900: "Managing complex emotions",
                                  1000: "Practicing self-reflection",
                              },
                              "Communication Skills": {
                                  100: "Using gestures to communicate",
                                  200: "Speaking in simple sentences",
                                  300: "Following basic instructions",
                                  400: "Listening actively",
                                  500: "Engaging in conversations",
                                  600: "Asking and answering questions",
                                  700: "Expressing ideas clearly",
                                  800: "Giving presentations",
                                  900: "Interpreting non-verbal cues",
                                  1000: "Practicing public speaking",
                              },
                              "Cognitive Skills": {
                                  100: "Playing simple memory games",
                                  200: "Completing puzzles",
                                  300: "Understanding cause and effect",
                                  400: "Using imaginative play",
                                  500: "Solving simple problems",
                                  600: "Making predictions",
                                  700: "Analyzing information",
                                  800: "Engaging in creative problem-solving",
                                  900: "Thinking critically",
                                  1000: "Applying logic to complex scenarios",
                              },
                              "Life Skills": {
                                  100: "Tidying up toys",
                                  200: "Following routines",
                                  300: "Completing simple chores",
                                  400: "Taking care of personal hygiene",
                                  500: "Managing time",
                                  600: "Handling responsibilities",
                                  700: "Organizing tasks",
                                  800: "Developing independence",
                                  900: "Practicing self-discipline",
                                  1000: "Setting and achieving goals",
                              },
                              "Physical Development": {
                                  100: "Crawling and walking",
                                  200: "Running and jumping",
                                  300: "Using fine motor skills (drawing, coloring)",
                                  400: "Climbing and balancing",
                                  500: "Riding a bicycle",
                                  600: "Playing sports",
                                  700: "Coordinating movements",
                                  800: "Practicing agility",
                                  900: "Improving overall fitness",
                                  1000: "Engaging in advanced physical activities",
    }
}

 
# add a couple new skills
# Interpersonal Relationships: Developing deeper relationships, understanding healthy relationships, and navigating peer pressure
# Personal Identity: Developing a sense of self, values, ethics, and beliefs.
# Career and Future Planning: Exploring career interests, goal setting, planning for higher education or vocational training, and work experience.
skill_thresholds_high_school = {
    "Academic Skills": {
        10: "Understanding basic algebra",
        20: "Writing structured essays",
        30: "Solving complex equations",
        40: "Analyzing literature",
        50: "Conducting scientific experiments",
        60: "Understanding historical events",
        70: "Applying critical thinking",
        80: "Creating research projects",
        90: "Mastering advanced mathematics",
        100: "Exploring college-level topics",
    },
    "Social Skills": {
        10: "Participating in group activities",
        20: "Building friendships",
        30: "Navigating peer pressure",
        40: "Understanding healthy relationships",
        50: "Collaborating on projects",
        60: "Handling conflicts",
        70: "Showing empathy",
        80: "Developing teamwork",
        90: "Building a support network",
        100: "Leading group initiatives",
    },
    "Emotional Skills": {
        10: "Recognizing emotions",
        20: "Managing stress",
        30: "Developing self-esteem",
        40: "Coping with academic pressure",
        50: "Handling rejection",
        60: "Practicing mindfulness",
        70: "Building resilience",
        80: "Understanding mental health",
        90: "Seeking help when needed",
        100: "Supporting others emotionally",
    },
    "Communication Skills": {
        10: "Speaking in front of a class",
        20: "Writing formal emails",
        30: "Engaging in debates",
        40: "Listening actively",
        50: "Giving presentations",
        60: "Interpreting non-verbal cues",
        70: "Expressing opinions clearly",
        80: "Participating in discussions",
        90: "Negotiating effectively",
        100: "Public speaking",
    },
    "Creativity": {
        10: "Drawing and painting",
        20: "Writing stories",
        30: "Performing arts (theater, music)",
        40: "Inventing solutions",
        50: "Designing projects",
        60: "Collaborating on creative tasks",
        70: "Thinking outside the box",
        80: "Developing unique ideas",
        90: "Creating portfolios",
        100: "Showcasing talents",
    },
    "Life Skills": {
        10: "Managing time",
        20: "Organizing tasks",
        30: "Taking responsibility",
        40: "Budgeting money",
        50: "Cooking simple meals",
        60: "Practicing self-care",
        70: "Handling chores",
        80: "Developing independence",
        90: "Setting goals",
        100: "Preparing for adulthood",
    },
    "Physical Development": {
        10: "Participating in sports",
        20: "Practicing coordination",
        30: "Improving endurance",
        40: "Building strength",
        50: "Enhancing flexibility",
        60: "Maintaining fitness",
        70: "Engaging in physical activities",
        80: "Developing motor skills",
        90: "Promoting overall health",
        100: "Achieving physical goals",
    },
    "Interpersonal Relationships": {
        10: "Making friends",
        20: "Building trust",
        30: "Understanding boundaries",
        40: "Practicing respect",
        50: "Showing kindness",
        60: "Navigating peer pressure",
        70: "Communicating effectively",
        80: "Developing deep connections",
        90: "Handling conflicts",
        100: "Maintaining healthy relationships",
    },
    "Personal Identity": {
        10: "Exploring interests",
        20: "Understanding values",
        30: "Building self-awareness",
        40: "Reflecting on beliefs",
        50: "Developing ethics",
        60: "Expressing individuality",
        70: "Setting personal goals",
        80: "Growing self-confidence",
        90: "Practicing self-reflection",
        100: "Embracing uniqueness",
    },
    "Career and Future Planning": {
        10: "Exploring career interests",
        20: "Setting academic goals",
        30: "Planning for higher education",
        40: "Participating in internships",
        50: "Building a resume",
        60: "Practicing job interviews",
        70: "Researching vocational training",
        80: "Developing job skills",
        90: "Networking with professionals",
        100: "Preparing for the future",
    }
}
